/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/

(function ($, Drupal) {
  Drupal.behaviors.batch = {
    attach: function attach(context, settings) {
      var batch = settings.batch;
      var $progress = $('[data-drupal-progress]').once('batch');
      var progressBar;

      function updateCallback(progress, status, pb) {
        if (progress === '100') {
          pb.stopMonitoring();

          $.ajax({
            url: "".concat(batch.uri, "&op=finished"),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            success: function success(value) {
              var $dialog = $('#drupal-modal');
              if ($dialog.length) {
                Drupal.dialog($dialog.get(0)).close();
                $dialog.remove();
              }
              // Unbind dialogButtonsChange.
              $dialog.off('dialogButtonsChange');


            }
          });



          //window.location = "".concat(batch.uri, "&op=finished");
        }
      }

      function errorCallback(pb) {
        $progress.prepend($('<p class="error"></p>').html(batch.errorMessage));
        $('#wait').hide();
      }

      if ($progress.length) {
        progressBar = new Drupal.ProgressBar('updateprogress', updateCallback, 'POST', errorCallback);
        progressBar.setProgress(-1, batch.initMessage);
        progressBar.startMonitoring("".concat(batch.uri, "&op=do"), 10);
        $progress.empty();
        $progress.append(progressBar.element);
      }
    }
  };
})(jQuery, Drupal);
