<?php

/**
 * @file
 * Entity reference actions module hooks.
 */

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_reference_actions\Form\ActionForm;

/**
 * Implements hook_field_widget_form_alter().
 */
function entity_reference_actions_field_widget_form_container_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\FieldDefinitionInterface $field_definition */
  $field_definition = $context['items']->getFieldDefinition();

  if ($field_definition->getType() === 'entity_reference') {
    $form = \Drupal::classResolver(ActionForm::class);
    $entity_type = $field_definition->getSettings()['target_type'];

    /** @var \Drupal\Core\Field\WidgetInterface $widget */
    $widget = $context['widget'];

    $form->init($entity_type, $widget->getThirdPartySettings('entity_reference_actions'));
    $form->formAlter($element, $form_state, $context);
  }
}

/**
 * Implements hook_field_widget_third_party_settings_form().
 */
function entity_reference_actions_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  $element = [];
  if ($field_definition->getType() === 'entity_reference') {
    $form = \Drupal::classResolver(ActionForm::class);
    $entity_type = $field_definition->getSettings()['target_type'];

    $form->init($entity_type, $plugin->getThirdPartySettings('entity_reference_actions'));
    $form->buildSettingsForm($element, $form_state, $field_definition->getName());
  }
  return $element;
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 */
function entity_reference_actions_field_widget_settings_summary_alter(&$summary, $context) {
  /** @var \Drupal\Core\Field\FieldDefinitionInterface $field_definition */
  $field_definition = $context['field_definition'];

  if ($field_definition->getType() === 'entity_reference') {
    $enabled = $context['widget']->getThirdPartySetting('entity_reference_actions', 'enabled');
    $summary[] = 'Entity Reference Actions: ' . ($enabled ? 'On' : 'Off');
  }
}
